name: devcontainer_${DEV_IMAGE:-code}

networks:
  proxy:
    name: ${NETWORK_NAME:-proxy}
    external: ${NETWORK_EXTERNAL:-false}

volumes:
  cache:
    name: devcontainer_shared_cache
    external: ${SHARED_VOLUMES:-false}
  local:
    name: devcontainer_shared_local
    external: ${SHARED_VOLUMES:-false}

services:
  devcontainer:
    profiles:
      - code
    build: .
    container_name: devcontainer
    image: vscode_devcontainer
    command: sleep infinity

    volumes:
      - ..:/workspaces:cached

    networks:
      proxy:

  debian-container:
    profiles:
      - debian
    build:
      context: .
      target: dev
      args:
        WORKSPACE_NAME: ${PROJECT_NAME:-code}
    image: dev_debian_${DEV_IMAGE:-code}:latest
    container_name: dev_debian_${DEV_IMAGE:-code}

    volumes:
      - ../:/workspaces/${PROJECT_NAME:-code}:cached
      - $HOME/.gitconfig:/home/dev/.gitconfig:ro
      - cache:/home/dev/.cache
      - local:/home/dev/.local

    networks:
      proxy:

  arch-container:
    profiles:
      - arch
    build:
      context: .
      target: arch
      args:
        WORKSPACE_NAME: ${PROJECT_NAME:-code}
    image: dev_arch_${DEV_IMAGE:-code}:latest
    container_name: dev_arch_${DEV_IMAGE:-code}

    volumes:
      - ../:/workspaces/${PROJECT_NAME:-code}:cached
      - $HOME/.gitconfig:/home/dev/.gitconfig:ro
      - cache:/home/dev/.cache
      - local:/home/dev/.local

    networks:
      proxy:
