cursor #e2e1ec
cursor_text_color #c4c5d6

foreground            #e2e1ec
background            #12131a
selection_foreground  #212d5b
selection_background  #b8c4fb
url_color             #b7c4ff

color0   #12131a
color1   #ff7297
color2   #7fff94
color3   #fff972
color4   #a0aef2
color5   #384376
color6   #b7c4ff
color7   #eff2ff
color8   #999ba5
color9   #ff9fb8
color10  #a5ffb4
color11  #fffba5
color12  #c1ccff
color13  #ccd5ff
color14  #dee4ff
color15  #f8f9ff
